---
- name: Install Mate Desktop Environment
  package:
    name: "@KDE Plasma Workspaces"
- name: Install pass
  package: name=pass
- name: Install xloadimage
  package: name=xloadimage
- name: Install Dunst
  package: name=dunst
- include_tasks: rofi.yml
- name: Install dev fonts
  package: name=dejavu-sans-mono-fonts
- name: Install external camera tools
  package: name=gvfs-mtp,gvfs-gphoto2,eog,darktable
#- package: name=engrampa
#- package: name=evince
- name: Install Qtpass
  package:
    name: qtpass
- name: Install transmission
  package:
    name: transmission
- include_tasks: sddm-common.yml
- name: Install i3
  package:
    name: i3
