---
- name: Check if gdm is installed
  command: rpm -q gdm
  register: gdm_installed
  failed_when: "false"
  changed_when: "false"
- name: Disable gdm
  service:
    name: gdm
    enabled: no
  when: gdm_installed.rc is defined and gdm_installed.rc == 0
- name: Check if lightdm is installed
  command: rpm -q lightdm
  register: lightdm_installed
  failed_when: "false"
  changed_when: "false"
- name: Disable lightdm
  service:
    name: lightdm
    enabled: no
  when: lightdm_installed.rc is defined and lightdm_installed.rc == 0
- name: Enable sddm
  service:
    name: sddm
    enabled: yes
