---
- name: Install pass
  package: name=pass
- name: Install Dunst
  package: name=dunst
- name: Install dev fonts
  package:
    name: dejavu-sans-mono-fonts,gdouros-symbola-fonts
- name: Install external camera tools
  package: name=gvfs-mtp,gvfs-gphoto2,eog,darktable,gvfs-smb,gvfs-fuse
  #python2-smbc
- package: name=engrampa
- package: name=evince
- package: name=qtpass
- package: name=transmission
- name: Install redshift
  package:
    name: redshift-gtk
- name: Install shotwell
  package:
    name: shotwell
- name: Install digikam
  package:
    name: digikam
- name: Install selinux troubleshooter
  package:
    name: setroubleshoot
- include_tasks: libreoffice.yml
