---
- name: Install xmonad
  package: name=xmonad-mate,xmonad,ghc-xmonad-contrib-devel
- name: Install haskell dbus dev package
  package: name=ghc-dbus-devel
- name: Ensure mate screensaver is removed
  package: name=mate-screensaver state=absent
- name: Install light locker
  package: name=light-locker
- name: Install caja
  package: name=caja,caja-open-terminal,caja-share
- name: Install picom
  package:
    name: picom
- include_tasks: rofi.yml
- name: Install xloadimage
  package: name=xloadimage
- name: Install nitrogen
  package:
    name: nitrogen
- name: Install dex-autostart
  package:
    name: dex-autostart
- name: Install mate-screenshot
  package:
    name: mate-screenshot

# TODO acpi??
